name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "SITE_URL=${{secrets.SITE_URL}}" >> .env && echo "NEXT_PUBLIC_GOOGLE_MAP_API_KEY=${{secrets.NEXT_PUBLIC_GOOGLE_MAP_API_KEY}}" >> .env
      - name: Build docker image
        run: docker build -t changwhioh/washroom2 .
      - name: Check env value to figure out error(for token and id)
        run: echo "DOCKERHUB_TOKEN=${{secrets.DOCKERHUB_TOKEN}}, DOCKERHUB_USERNAME=${{secrets.DOCKERHUB_USERNAME}}"
      - name: Login to docker hub
        run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - name: Publish image to docker hub
        run: docker push changwhioh/washroom2:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull changwhioh/washroom2:latest
      - name: Delete old container
        run: docker rm -f washroom2
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name washroom2 changwhioh/washroom2